/* ==========================================================================
   learn.js — learning content. Argument/attribute lists are the commonly
   used subset of each resource's Registry page, not the full schema.
   ========================================================================== */
const RES_INFO = {
  aws_vpc: ['Creates an Amazon VPC: a private, isolated network with its own IP range.', ['cidr_block', 'enable_dns_support', 'enable_dns_hostnames', 'instance_tenancy', 'tags'], ['id', 'arn', 'cidr_block', 'default_route_table_id', 'main_route_table_id']],
  aws_subnet: ['Creates a subnet: a slice of the VPC CIDR that lives in exactly one Availability Zone.', ['vpc_id', 'cidr_block', 'availability_zone', 'map_public_ip_on_launch', 'tags'], ['id', 'arn', 'availability_zone', 'cidr_block']],
  aws_route_table: ['A set of routes deciding where traffic from associated subnets goes.', ['vpc_id', 'route', 'tags'], ['id', 'arn']],
  aws_route_table_association: ['Links one subnet to one route table.', ['subnet_id', 'route_table_id', 'gateway_id'], ['id']],
  aws_internet_gateway: ['Attaches internet connectivity to a VPC.', ['vpc_id', 'tags'], ['id', 'arn']],
  aws_nat_gateway: ['Managed NAT so private subnets can start outbound connections.', ['allocation_id', 'subnet_id', 'connectivity_type', 'tags'], ['id', 'public_ip', 'private_ip', 'network_interface_id']],
  aws_eip: ['Allocates a static public IPv4 address.', ['domain', 'instance', 'network_interface', 'tags'], ['id', 'allocation_id', 'public_ip']],
  aws_security_group: ['A stateful virtual firewall attached to network interfaces.', ['name', 'name_prefix', 'description', 'vpc_id', 'tags'], ['id', 'arn', 'name', 'owner_id']],
  aws_vpc_security_group_ingress_rule: ['One inbound rule on a security group, managed as its own resource.', ['security_group_id', 'ip_protocol', 'from_port', 'to_port', 'cidr_ipv4', 'referenced_security_group_id', 'description'], ['id', 'arn', 'security_group_rule_id']],
  aws_vpc_security_group_egress_rule: ['One outbound rule on a security group.', ['security_group_id', 'ip_protocol', 'cidr_ipv4', 'from_port', 'to_port'], ['id', 'arn', 'security_group_rule_id']],
  aws_network_acl: ['A stateless, numbered rule list applied at the subnet boundary.', ['vpc_id', 'subnet_ids', 'ingress', 'egress', 'tags'], ['id', 'arn']],
  aws_vpc_endpoint: ['Private connectivity from the VPC to an AWS service.', ['vpc_id', 'service_name', 'vpc_endpoint_type', 'route_table_ids', 'subnet_ids', 'private_dns_enabled'], ['id', 'arn', 'prefix_list_id', 'dns_entry']],
  aws_ec2_transit_gateway: ['A regional network hub for VPCs and VPNs.', ['description', 'amazon_side_asn', 'default_route_table_association', 'default_route_table_propagation', 'dns_support'], ['id', 'arn', 'association_default_route_table_id']],
  aws_ec2_transit_gateway_vpc_attachment: ['Connects a VPC to a transit gateway through chosen subnets.', ['transit_gateway_id', 'vpc_id', 'subnet_ids'], ['id', 'vpc_owner_id']],
  aws_lb: ['An Elastic Load Balancer. load_balancer_type chooses application, network or gateway.', ['name', 'internal', 'load_balancer_type', 'security_groups', 'subnets', 'enable_deletion_protection'], ['arn', 'dns_name', 'zone_id', 'arn_suffix']],
  aws_lb_target_group: ['A group of targets plus the health check that decides who gets traffic.', ['name', 'port', 'protocol', 'target_type', 'vpc_id', 'health_check'], ['arn', 'arn_suffix', 'name']],
  aws_lb_target_group_attachment: ['Registers a single target (instance, IP or Lambda) in a target group.', ['target_group_arn', 'target_id', 'port'], ['id']],
  aws_lb_listener: ['A port and protocol on a load balancer, with a default action.', ['load_balancer_arn', 'port', 'protocol', 'ssl_policy', 'certificate_arn', 'default_action'], ['arn', 'id']],
  aws_route53_zone: ['A hosted zone that answers DNS queries for a domain.', ['name', 'comment', 'vpc', 'force_destroy'], ['zone_id', 'name_servers', 'arn']],
  aws_route53_record: ['A DNS record in a hosted zone; alias records point at AWS resources.', ['zone_id', 'name', 'type', 'ttl', 'records', 'alias'], ['fqdn', 'name']],
  aws_wafv2_web_acl: ['A WAF web ACL: ordered rules that allow, block or count requests.', ['name', 'scope', 'default_action', 'rule', 'visibility_config'], ['arn', 'id', 'capacity']],
  aws_wafv2_web_acl_association: ['Attaches a regional web ACL to an ALB, API Gateway stage or similar.', ['resource_arn', 'web_acl_arn'], ['id']],
  aws_cloudfront_distribution: ['A CloudFront CDN distribution with origins and cache behaviours.', ['enabled', 'origin', 'default_cache_behavior', 'price_class', 'restrictions', 'viewer_certificate', 'web_acl_id'], ['id', 'arn', 'domain_name', 'hosted_zone_id']],
  aws_cloudfront_origin_access_control: ['Lets CloudFront sign requests to a private S3 origin.', ['name', 'origin_access_control_origin_type', 'signing_behavior', 'signing_protocol'], ['id', 'etag']],
  aws_s3_bucket_policy: ['A resource policy attached to a bucket.', ['bucket', 'policy'], ['id']],
  aws_vpn_gateway: ['The AWS side of a site-to-site VPN, attached to a VPC.', ['vpc_id', 'amazon_side_asn', 'tags'], ['id', 'arn']],
  aws_customer_gateway: ['Metadata about your on-premises VPN device.', ['bgp_asn', 'ip_address', 'type', 'tags'], ['id', 'arn']],
  aws_vpn_connection: ['An IPsec VPN with two tunnels for redundancy.', ['customer_gateway_id', 'vpn_gateway_id', 'transit_gateway_id', 'type', 'static_routes_only'], ['id', 'arn', 'tunnel1_address', 'tunnel2_address']],
  aws_instance: ['Launches an EC2 virtual machine.', ['ami', 'instance_type', 'subnet_id', 'vpc_security_group_ids', 'iam_instance_profile', 'metadata_options', 'root_block_device', 'tags'], ['id', 'arn', 'private_ip', 'public_ip', 'availability_zone']],
  aws_launch_template: ['A versioned template of instance settings.', ['name_prefix', 'image_id', 'instance_type', 'vpc_security_group_ids', 'iam_instance_profile', 'metadata_options', 'block_device_mappings'], ['id', 'arn', 'latest_version', 'default_version']],
  aws_autoscaling_group: ['Maintains a fleet of instances between min and max size.', ['min_size', 'max_size', 'desired_capacity', 'vpc_zone_identifier', 'launch_template', 'target_group_arns', 'health_check_type'], ['id', 'name', 'arn']],
  aws_lambda_function: ['A serverless function that runs your code on demand.', ['function_name', 'role', 'runtime', 'handler', 'filename', 'source_code_hash', 'memory_size', 'timeout', 'vpc_config'], ['arn', 'invoke_arn', 'qualified_arn', 'version']],
  aws_cloudwatch_log_group: ['A CloudWatch Logs group with a retention period.', ['name', 'retention_in_days', 'kms_key_id'], ['arn']],
  aws_iam_role: ['An IAM identity that trusted principals assume for temporary credentials.', ['name', 'name_prefix', 'assume_role_policy', 'max_session_duration', 'description'], ['arn', 'name', 'unique_id']],
  aws_iam_role_policy_attachment: ['Attaches a managed policy to a role.', ['role', 'policy_arn'], ['id']],
  aws_iam_instance_profile: ['The container that lets an EC2 instance use an IAM role.', ['name', 'name_prefix', 'role'], ['arn', 'id', 'unique_id']],
  aws_iam_policy: ['A customer managed IAM policy document.', ['name', 'name_prefix', 'description', 'policy'], ['arn', 'id', 'policy_id']],
  aws_ecs_cluster: ['A logical grouping of ECS services and tasks.', ['name', 'setting', 'configuration'], ['arn', 'id', 'name']],
  aws_ecs_task_definition: ['Describes the containers ECS should run.', ['family', 'requires_compatibilities', 'network_mode', 'cpu', 'memory', 'execution_role_arn', 'container_definitions'], ['arn', 'revision', 'family']],
  aws_ecs_service: ['Keeps a number of task copies running and registered with a load balancer.', ['name', 'cluster', 'task_definition', 'desired_count', 'launch_type', 'network_configuration', 'load_balancer'], ['id', 'name', 'cluster']],
  aws_eks_cluster: ['A managed Kubernetes control plane.', ['name', 'role_arn', 'version', 'vpc_config', 'access_config', 'encryption_config'], ['arn', 'endpoint', 'certificate_authority', 'identity', 'status']],
  aws_eks_node_group: ['A managed group of EC2 worker nodes for an EKS cluster.', ['cluster_name', 'node_group_name', 'node_role_arn', 'subnet_ids', 'instance_types', 'scaling_config'], ['arn', 'id', 'status', 'resources']],
  aws_ecr_repository: ['A private container image repository.', ['name', 'image_tag_mutability', 'image_scanning_configuration', 'encryption_configuration'], ['arn', 'repository_url', 'registry_id']],
  aws_ecr_lifecycle_policy: ['Rules that expire old or untagged images.', ['repository', 'policy'], ['repository', 'registry_id']],
  aws_ssm_parameter: ['A Parameter Store value (String, StringList or SecureString).', ['name', 'type', 'value', 'tier', 'description'], ['arn', 'version']],
  aws_db_subnet_group: ['Subnets across AZs that RDS may place databases into.', ['name', 'name_prefix', 'subnet_ids', 'description'], ['id', 'arn', 'name']],
  aws_db_instance: ['A single RDS database instance. The engine argument picks PostgreSQL, MySQL, MariaDB, Oracle or SQL Server.', ['engine', 'engine_version', 'instance_class', 'allocated_storage', 'username', 'manage_master_user_password', 'db_subnet_group_name', 'multi_az', 'storage_encrypted'], ['address', 'endpoint', 'port', 'arn', 'master_user_secret']],
  aws_rds_cluster: ['An Aurora cluster: shared storage plus cluster endpoints.', ['cluster_identifier', 'engine', 'engine_version', 'database_name', 'master_username', 'manage_master_user_password', 'db_subnet_group_name'], ['endpoint', 'reader_endpoint', 'arn', 'master_user_secret']],
  aws_rds_cluster_instance: ['A compute instance inside an Aurora cluster.', ['cluster_identifier', 'instance_class', 'engine', 'identifier'], ['endpoint', 'writer', 'arn']],
  aws_dynamodb_table: ['A DynamoDB table defined by its keys and capacity mode.', ['name', 'billing_mode', 'hash_key', 'range_key', 'attribute', 'point_in_time_recovery', 'server_side_encryption'], ['arn', 'id', 'stream_arn']],
  aws_elasticache_subnet_group: ['Subnets ElastiCache may use.', ['name', 'subnet_ids'], ['id']],
  aws_elasticache_replication_group: ['A Valkey or Redis OSS primary with replicas.', ['replication_group_id', 'engine', 'node_type', 'num_cache_clusters', 'automatic_failover_enabled', 'transit_encryption_enabled'], ['primary_endpoint_address', 'reader_endpoint_address', 'arn']],
  aws_memorydb_subnet_group: ['Subnets MemoryDB may use.', ['name', 'subnet_ids'], ['id', 'arn']],
  aws_memorydb_cluster: ['A durable in-memory database cluster.', ['name', 'acl_name', 'node_type', 'num_shards', 'num_replicas_per_shard', 'tls_enabled'], ['arn', 'cluster_endpoint', 'shards']],
  aws_s3_bucket: ['An S3 bucket. Versioning, encryption and lifecycle are separate resources since provider v4.', ['bucket', 'bucket_prefix', 'force_destroy', 'tags'], ['id', 'arn', 'bucket', 'bucket_regional_domain_name']],
  aws_s3_bucket_public_access_block: ['Blocks public ACLs and policies on a bucket.', ['bucket', 'block_public_acls', 'block_public_policy', 'ignore_public_acls', 'restrict_public_buckets'], ['id']],
  aws_s3_bucket_ownership_controls: ['Controls object ownership; BucketOwnerEnforced disables ACLs.', ['bucket', 'rule'], ['id']],
  aws_s3_bucket_versioning: ['Turns object versioning on or suspends it.', ['bucket', 'versioning_configuration'], ['id']],
  aws_s3_bucket_server_side_encryption_configuration: ['Default encryption for new objects in a bucket.', ['bucket', 'rule'], ['id']],
  aws_s3_bucket_lifecycle_configuration: ['Rules that transition or expire objects over time.', ['bucket', 'rule'], ['id']],
  aws_ebs_volume: ['A block storage volume in one AZ.', ['availability_zone', 'size', 'type', 'iops', 'throughput', 'encrypted', 'kms_key_id'], ['id', 'arn']],
  aws_volume_attachment: ['Attaches an EBS volume to an instance.', ['device_name', 'volume_id', 'instance_id'], ['id']],
  aws_efs_file_system: ['A managed NFS file system.', ['creation_token', 'encrypted', 'performance_mode', 'throughput_mode', 'lifecycle_policy'], ['id', 'arn', 'dns_name']],
  aws_efs_mount_target: ['An NFS endpoint for the file system inside one subnet.', ['file_system_id', 'subnet_id', 'security_groups'], ['id', 'dns_name', 'ip_address']],
  aws_fsx_lustre_file_system: ['A Lustre parallel file system.', ['storage_capacity', 'subnet_ids', 'deployment_type', 'per_unit_storage_throughput', 'security_group_ids'], ['id', 'arn', 'dns_name', 'mount_name']],
  aws_backup_vault: ['An encrypted container for recovery points.', ['name', 'kms_key_arn'], ['arn', 'recovery_points']],
  aws_backup_plan: ['Schedules and retention rules for backups.', ['name', 'rule'], ['id', 'arn', 'version']],
  aws_backup_selection: ['Which resources a backup plan protects.', ['name', 'plan_id', 'iam_role_arn', 'resources', 'selection_tag'], ['id']],
  aws_kms_key: ['A customer managed encryption key.', ['description', 'enable_key_rotation', 'deletion_window_in_days', 'policy'], ['arn', 'key_id']],
  aws_kms_alias: ['A friendly name for a KMS key.', ['name', 'target_key_id'], ['arn', 'target_key_arn']],
  'data.aws_availability_zones': ['Looks up the Availability Zones available in the current region.', ['state', 'filter'], ['names', 'zone_ids']],
  'data.aws_ami': ['Finds an AMI ID by filters, so you never hard-code AMI IDs.', ['most_recent', 'owners', 'filter'], ['id', 'name', 'architecture']],
  'data.aws_iam_policy_document': ['Builds IAM policy JSON from HCL blocks; validated at plan time.', ['statement'], ['json']],
  'data.aws_caller_identity': ['Returns the account ID and ARN of the credentials Terraform is using.', [], ['account_id', 'arn', 'user_id']],
  'data.aws_cloudfront_cache_policy': ['Looks up a CloudFront cache policy, such as the AWS managed ones.', ['name', 'id'], ['id', 'etag']],
  'data.aws_cloudfront_origin_request_policy': ['Looks up a CloudFront origin request policy.', ['name', 'id'], ['id', 'etag']],
  'data.archive_file': ['From the hashicorp/archive provider: zips a directory at plan time.', ['type', 'source_dir', 'output_path'], ['output_path', 'output_base64sha256']],
};
function resDoc(t) { return t.startsWith('data.') ? docUrl(t) : docUrl(t); }

const TOPICS = [
  ['Beginner', 'Terraform', 'A tool that reads .tf files describing the infrastructure you want, compares that with what exists, and makes the changes. You describe the end state; Terraform works out the steps.', ''],
  ['Beginner', 'Providers', 'Plugins that teach Terraform how to talk to an API. hashicorp/aws translates resources into AWS API calls. Pin a version range so upgrades are deliberate.', 'required_providers {\n  aws = {\n    source  = "hashicorp/aws"\n    version = "~> 6.0"\n  }\n}'],
  ['Beginner', 'Resources', 'The things Terraform creates and manages. The first label is the type (from the provider), the second is your local name. Together they form an address like aws_vpc.main.', 'resource "aws_vpc" "main" {\n  cidr_block = "10.0.0.0/16"\n}'],
  ['Beginner', 'Variables', 'Inputs to your configuration, with a type, description and optional default and validation. Set them in terraform.tfvars, with -var, or TF_VAR_ environment variables.', 'variable "vpc_cidr" {\n  type    = string\n  default = "10.0.0.0/16"\n}'],
  ['Beginner', 'Outputs', 'Values Terraform prints after apply and exposes to other configurations, such as an endpoint or ID.', 'output "vpc_id" {\n  value = aws_vpc.main.id\n}'],
  ['Beginner', 'Data sources', 'Read-only lookups of things that already exist or are computed, such as the latest AMI or your account ID. They never create anything.', 'data "aws_caller_identity" "current" {}'],
  ['Beginner', 'Terraform state', 'A JSON record mapping each resource address to a real object ID. Terraform diffs config against state to plan. State can contain secrets, so keep it in an encrypted remote backend, never in Git.', ''],
  ['Beginner', 'terraform init', 'Downloads providers and modules and configures the backend. Run it first, and again whenever providers, modules or backend settings change.', 'terraform init'],
  ['Beginner', 'terraform plan', 'Shows what would change without changing anything. Read it every time: "+" create, "~" update in place, "-/+" replace, "-" destroy.', 'terraform plan -out=tfplan'],
  ['Beginner', 'terraform apply', 'Makes the planned changes. Applying a saved plan file guarantees you get exactly what you reviewed.', 'terraform apply tfplan'],
  ['Beginner', 'terraform destroy', 'Deletes everything in the state. Deletion protection on databases or load balancers will block it until you turn protection off.', 'terraform destroy'],
  ['Intermediate', 'Modules', 'A folder of .tf files with inputs and outputs that you call from another configuration. Every configuration is a module; the one you run is the root module.', 'module "vpc" {\n  source = "terraform-aws-modules/vpc/aws"\n  # version = "<pin from the Registry>"\n  name = "demo"\n  cidr = "10.0.0.0/16"\n}'],
  ['Intermediate', 'Locals', 'Named expressions computed once and reused, like a naming prefix or a merged tag map. Unlike variables, callers cannot override them.', 'locals {\n  name_prefix = "${var.project_name}-${var.environment}"\n}'],
  ['Intermediate', 'for_each', 'Creates one instance per map key or set element, addressed by key (aws_subnet.private["private-a"]). Removing one key only affects that instance, which is why it beats count for most collections.', 'resource "aws_subnet" "private" {\n  for_each   = var.private_subnets\n  cidr_block = each.value.cidr_block\n  vpc_id     = aws_vpc.main.id\n}'],
  ['Intermediate', 'count', 'Creates N numbered copies (aws_rds_cluster_instance.main[0]). Good for identical replicas or on/off toggles; poor for lists that change order, because indexes shift.', 'count = var.create_bastion ? 1 : 0'],
  ['Intermediate', 'dynamic blocks', 'Generate repeated nested blocks from a collection. Use sparingly: they make code harder to read.', 'dynamic "attribute" {\n  for_each = var.range_key == null ? [] : [var.range_key]\n  content {\n    name = attribute.value\n    type = "S"\n  }\n}'],
  ['Intermediate', 'depends_on', 'Forces ordering when Terraform cannot see a dependency through references. Most dependencies are implicit: referencing aws_vpc.main.id already makes the subnet wait for the VPC.', 'depends_on = [aws_internet_gateway.main]'],
  ['Intermediate', 'lifecycle', 'Changes how Terraform replaces or updates a resource: create_before_destroy, prevent_destroy, ignore_changes and replace_triggered_by.', 'lifecycle {\n  ignore_changes = [desired_capacity]\n}'],
  ['Intermediate', 'Remote state', 'Store state in S3 so a team shares one source of truth. From Terraform 1.10, S3 supports native locking with use_lockfile, so a DynamoDB lock table is no longer required.', 'backend "s3" {\n  bucket       = "my-tf-state"\n  key          = "app/terraform.tfstate"\n  region       = "ap-southeast-1"\n  use_lockfile = true\n}'],
  ['Advanced', 'Module design', 'Keep modules small and single-purpose, expose only the inputs callers need, output IDs and ARNs, avoid provider blocks inside child modules, and version them with semantic tags.', ''],
  ['Advanced', 'State management', 'Split state by blast radius (network, data, app) and lifecycle. Use moved blocks to rename safely, import blocks to adopt existing resources, and removed blocks to stop managing something without destroying it.', 'moved {\n  from = aws_instance.web\n  to   = aws_instance.main\n}'],
  ['Advanced', 'Workspaces', 'Multiple state files for one configuration. Handy for short-lived copies; for dev/staging/prod most teams prefer separate directories or accounts so permissions and backends differ.', 'terraform workspace new staging'],
  ['Advanced', 'Provider aliases', 'A second configuration of the same provider, for another region or account. Resources choose it with provider = aws.<alias>.', 'provider "aws" {\n  alias  = "us_east_1"\n  region = "us-east-1"\n}'],
  ['Advanced', 'Multi-account AWS', 'In a Control Tower or Organizations landing zone, Terraform runs with one identity and assumes a role in each target account.', 'provider "aws" {\n  alias  = "workload"\n  region = var.aws_region\n  assume_role {\n    role_arn = "arn:aws:iam::111122223333:role/TerraformDeploy"\n  }\n}'],
  ['Advanced', 'Multi-region AWS', 'Use one provider alias per region and pass providers into modules explicitly, or deploy the same root module per region with different variables.', 'module "dr" {\n  source    = "./modules/app"\n  providers = { aws = aws.dr }\n}'],
  ['Advanced', 'CI/CD', 'Run fmt, validate, plan on every pull request and apply only from the main branch with a reviewed plan. Authenticate with OIDC federation to an IAM role instead of stored keys.', ''],
  ['Advanced', 'HCP Terraform', 'HashiCorp\'s hosted service (formerly Terraform Cloud) that stores state, runs plans remotely, and adds policy checks and a private registry.', 'terraform {\n  cloud {\n    organization = "my-org"\n    workspaces { name = "network-dev" }\n  }\n}'],
  ['Advanced', 'State locking', 'Prevents two applies from writing the same state at once. S3 with use_lockfile, HCP Terraform and most backends lock automatically.', ''],
  ['Advanced', 'Security best practices', 'No credentials in code; least-privilege IAM; encrypt state and resources; mark secret outputs sensitive; scan with tools like tflint, checkov or trivy; pin provider and module versions; review every plan.', ''],
];

const CLI = [
  ['terraform init', 'Downloads the AWS and archive providers and prepares the working directory.'],
  ['terraform fmt', 'Rewrites files into canonical style. Use -check in CI to fail on unformatted code.'],
  ['terraform validate', 'Checks syntax, references and argument names against the provider schema. It needs init first and does not call AWS.'],
  ['terraform plan -out=tfplan', 'Compares your code with state and AWS, and saves the exact change set for review.'],
  ['terraform apply tfplan', 'Makes the reviewed changes. Without a plan file, apply plans again and asks for confirmation.'],
  ['terraform output', 'Prints outputs such as the ALB DNS name or database endpoint.'],
  ['terraform destroy', 'Removes everything this configuration created. Turn off deletion protection first.'],
];

const AUTH = [
  ['IAM Identity Center (AWS SSO)', 'Recommended for people. Run aws configure sso once, then aws sso login; export AWS_PROFILE to pick the profile.', 'aws sso login --profile learning\nexport AWS_PROFILE=learning'],
  ['AWS CLI profile', 'Named profiles in ~/.aws/config. Terraform reads AWS_PROFILE automatically; you do not need to set profile in the provider block.', 'export AWS_PROFILE=learning'],
  ['Environment variables', 'Short-lived credentials from STS can be exported as AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN. Never paste long-lived keys into .tf files.', ''],
  ['IAM role', 'On EC2, ECS, CodeBuild or a CI runner using OIDC, the provider picks up role credentials automatically. This is how pipelines should deploy.', ''],
];

// Community modules maintained by the terraform-aws-modules project on the Registry.
// Versions are intentionally not hard-coded here; pin the current one from the Registry page.
const MODULES = {
  vpc: { m: 'vpc', covers: ['vpc', 'subnet', 'route_table', 'igw', 'nat', 'eip', 'nacl', 'vgw'], inputs: ['name', 'cidr', 'azs', 'private_subnets', 'public_subnets', 'enable_nat_gateway', 'single_nat_gateway'], outputs: ['vpc_id', 'private_subnets', 'public_subnets', 'natgw_ids'] },
  vpc_endpoint: { m: 'vpc', sub: 'modules/vpc-endpoints', covers: ['vpc_endpoint'], inputs: ['vpc_id', 'endpoints'], outputs: ['endpoints'] },
  sg: { m: 'security-group', covers: ['sg'], inputs: ['name', 'vpc_id', 'ingress_cidr_blocks', 'ingress_rules', 'egress_rules'], outputs: ['security_group_id'] },
  tgw: { m: 'transit-gateway', covers: ['tgw', 'tgw_attach'] },
  alb: { m: 'alb', covers: ['alb', 'nlb', 'tg', 'listener'], inputs: ['name', 'load_balancer_type', 'vpc_id', 'subnets', 'listeners', 'target_groups'], outputs: ['arn', 'dns_name', 'target_groups'] },
  route53: { m: 'route53', covers: ['route53_zone', 'route53_record'] },
  cloudfront: { m: 'cloudfront', covers: ['cloudfront'] },
  vpn: { m: 'vpn-gateway', covers: ['vpn', 'cgw'] },
  ec2: { m: 'ec2-instance', covers: ['ec2'], inputs: ['name', 'ami', 'instance_type', 'subnet_id', 'vpc_security_group_ids'], outputs: ['id', 'private_ip', 'arn'] },
  asg: { m: 'autoscaling', covers: ['asg', 'lt'] },
  lambda: { m: 'lambda', covers: ['lambda'], inputs: ['function_name', 'handler', 'runtime', 'source_path'], outputs: ['lambda_function_arn', 'lambda_function_name'] },
  ecs: { m: 'ecs', covers: ['ecs_cluster', 'ecs_task', 'ecs_service'] },
  eks: { m: 'eks', covers: ['eks_cluster', 'eks_node_group'] },
  ecr: { m: 'ecr', covers: ['ecr'] },
  iam: { m: 'iam', covers: ['iam_role', 'iam_policy'] },
  ssm: { m: 'ssm-parameter', covers: ['ssm'] },
  rds: { m: 'rds', covers: ['rds', 'rds_postgres', 'rds_mysql', 'rds_sqlserver', 'dbsg'], inputs: ['identifier', 'engine', 'engine_version', 'instance_class', 'allocated_storage', 'db_subnet_group_name'], outputs: ['db_instance_endpoint', 'db_instance_arn'] },
  aurora: { m: 'rds-aurora', covers: ['aurora'] },
  dynamodb: { m: 'dynamodb-table', covers: ['dynamodb'], inputs: ['name', 'hash_key', 'range_key', 'attributes'], outputs: ['dynamodb_table_arn', 'dynamodb_table_id'] },
  elasticache: { m: 'elasticache', covers: ['elasticache'] },
  memorydb: { m: 'memory-db', covers: ['memorydb'] },
  s3: { m: 's3-bucket', covers: ['s3', 's3_versioning', 's3_encryption', 's3_lifecycle'], inputs: ['bucket', 'versioning', 'server_side_encryption_configuration', 'lifecycle_rule'], outputs: ['s3_bucket_id', 's3_bucket_arn'] },
  efs: { m: 'efs', covers: ['efs'] },
  fsx: { m: 'fsx', covers: ['fsx'] },
  kms: { m: 'kms', covers: ['kms'] },
};
function moduleFor(svcId) { for (const [k, v] of Object.entries(MODULES)) if (v.covers.includes(svcId)) return Object.assign({ key: k }, v); return null; }
function moduleUrl(m) { return `https://registry.terraform.io/modules/terraform-aws-modules/${m.m}/aws/latest` + (m.sub ? '/submodules/' + m.sub.split('/').pop() : ''); }
