/* ==========================================================================
   learn.js — learning content. Argument/attribute lists are the commonly
   used subset of each resource's Registry page, not the full schema.
   ========================================================================== */
const RES_INFO = {
  aws_vpc: ['Creates an Amazon VPC: a private, isolated network with its own IP range.', ['cidr_block', 'enable_dns_support', 'enable_dns_hostnames', 'instance_tenancy', 'tags'], ['id', 'arn', 'cidr_block', 'default_route_table_id', 'main_route_table_id']],
  aws_subnet: ['Creates a subnet: a slice of the VPC CIDR that lives in exactly one Availability Zone.', ['vpc_id', 'cidr_block', 'availability_zone', 'map_public_ip_on_launch', 'tags'], ['id', 'arn', 'availability_zone', 'cidr_block']],
  aws_route_table: ['A set of routes deciding where traffic from associated subnets goes.', ['vpc_id', 'route', 'tags'], ['id', 'arn']],
  aws_route_table_association: ['Links one subnet to one route table.', ['subnet_id', 'route_table_id', 'gateway_id'], ['id']],
  aws_internet_gateway: ['Attaches internet connectivity to a VPC.', ['vpc_id', 'tags'], ['id', 'arn']],
  aws_nat_gateway: ['Managed NAT so private subnets can start outbound connections.', ['allocation_id', 'subnet_id', 'connectivity_type', 'tags'], ['id', 'public_ip', 'private_ip', 'network_interface_id']],
  aws_eip: ['Allocates a static public IPv4 address.', ['domain', 'instance', 'network_interface', 'tags'], ['id', 'allocation_id', 'public_ip']],
  aws_security_group: ['A stateful virtual firewall attached to network interfaces.', ['name', 'name_prefix', 'description', 'vpc_id', 'tags'], ['id', 'arn', 'name', 'owner_id']],
  aws_vpc_security_group_ingress_rule: ['One inbound rule on a security group, managed as its own resource.', ['security_group_id', 'ip_protocol', 'from_port', 'to_port', 'cidr_ipv4', 'referenced_security_group_id', 'description'], ['id', 'arn', 'security_group_rule_id']],
  aws_vpc_security_group_egress_rule: ['One outbound rule on a security group.', ['security_group_id', 'ip_protocol', 'cidr_ipv4', 'from_port', 'to_port'], ['id', 'arn', 'security_group_rule_id']],
  aws_network_acl: ['A stateless, numbered rule list applied at the subnet boundary.', ['vpc_id', 'subnet_ids', 'ingress', 'egress', 'tags'], ['id', 'arn']],
  aws_vpc_endpoint: ['Private connectivity from the VPC to an AWS service.', ['vpc_id', 'service_name', 'vpc_endpoint_type', 'route_table_ids', 'subnet_ids', 'private_dns_enabled'], ['id', 'arn', 'prefix_list_id', 'dns_entry']],
  aws_ec2_transit_gateway: ['A regional network hub for VPCs and VPNs.', ['description', 'amazon_side_asn', 'default_route_table_association', 'default_route_table_propagation', 'dns_support'], ['id', 'arn', 'association_default_route_table_id']],
  aws_ec2_transit_gateway_vpc_attachment: ['Connects a VPC to a transit gateway through chosen subnets.', ['transit_gateway_id', 'vpc_id', 'subnet_ids'], ['id', 'vpc_owner_id']],
  aws_lb: ['An Elastic Load Balancer. load_balancer_type chooses application, network or gateway.', ['name', 'internal', 'load_balancer_type', 'security_groups', 'subnets', 'enable_deletion_protection'], ['arn', 'dns_name', 'zone_id', 'arn_suffix']],
  aws_lb_target_group: ['A group of targets plus the health check that decides who gets traffic.', ['name', 'port', 'protocol', 'target_type', 'vpc_id', 'health_check'], ['arn', 'arn_suffix', 'name']],
  aws_lb_target_group_attachment: ['Registers a single target (instance, IP or Lambda) in a target group.', ['target_group_arn', 'target_id', 'port'], ['id']],
  aws_lb_listener: ['A port and protocol on a load balancer, with a default action.', ['load_balancer_arn', 'port', 'protocol', 'ssl_policy', 'certificate_arn', 'default_action'], ['arn', 'id']],
  aws_route53_zone: ['A hosted zone that answers DNS queries for a domain.', ['name', 'comment', 'vpc', 'force_destroy'], ['zone_id', 'name_servers', 'arn']],
  aws_route53_record: ['A DNS record in a hosted zone; alias records point at AWS resources.', ['zone_id', 'name', 'type', 'ttl', 'records', 'alias'], ['fqdn', 'name']],
  aws_wafv2_web_acl: ['A WAF web ACL: ordered rules that allow, block or count requests.', ['name', 'scope', 'default_action', 'rule', 'visibility_config'], ['arn', 'id', 'capacity']],
  aws_wafv2_web_acl_association: ['Attaches a regional web ACL to an ALB, API Gateway stage or similar.', ['resource_arn', 'web_acl_arn'], ['id']],
  aws_cloudfront_distribution: ['A CloudFront CDN distribution with origins and cache behaviours.', ['enabled', 'origin', 'default_cache_behavior', 'price_class', 'restrictions', 'viewer_certificate', 'web_acl_id'], ['id', 'arn', 'domain_name', 'hosted_zone_id']],
  aws_cloudfront_origin_access_control: ['Lets CloudFront sign requests to a private S3 origin.', ['name', 'origin_access_control_origin_type', 'signing_behavior', 'signing_protocol'], ['id', 'etag']],
  aws_s3_bucket_policy: ['A resource policy attached to a bucket.', ['bucket', 'policy'], ['id']],
  aws_vpn_gateway: ['The AWS side of a site-to-site VPN, attached to a VPC.', ['vpc_id', 'amazon_side_asn', 'tags'], ['id', 'arn']],
  aws_customer_gateway: ['Metadata about your on-premises VPN device.', ['bgp_asn', 'ip_address', 'type', 'tags'], ['id', 'arn']],
  aws_vpn_connection: ['An IPsec VPN with two tunnels for redundancy.', ['customer_gateway_id', 'vpn_gateway_id', 'transit_gateway_id', 'type', 'static_routes_only'], ['id', 'arn', 'tunnel1_address', 'tunnel2_address']],
  aws_instance: ['Launches an EC2 virtual machine.', ['ami', 'instance_type', 'subnet_id', 'vpc_security_group_ids', 'iam_instance_profile', 'metadata_options', 'root_block_device', 'tags'], ['id', 'arn', 'private_ip', 'public_ip', 'availability_zone']],
  aws_launch_template: ['A versioned template of instance settings.', ['name_prefix', 'image_id', 'instance_type', 'vpc_security_group_ids', 'iam_instance_profile', 'metadata_options', 'block_device_mappings'], ['id', 'arn', 'latest_version', 'default_version']],
  aws_autoscaling_group: ['Maintains a fleet of instances between min and max size.', ['min_size', 'max_size', 'desired_capacity', 'vpc_zone_identifier', 'launch_template', 'target_group_arns', 'health_check_type'], ['id', 'name', 'arn']],
  aws_lambda_function: ['A serverless function that runs your code on demand.', ['function_name', 'role', 'runtime', 'handler', 'filename', 'source_code_hash', 'memory_size', 'timeout', 'vpc_config'], ['arn', 'invoke_arn', 'qualified_arn', 'version']],
  aws_cloudwatch_log_group: ['A CloudWatch Logs group: the container for log streams, with its retention, log class and encryption.', ['name', 'retention_in_days', 'log_group_class', 'kms_key_id', 'skip_destroy'], ['arn']],
  aws_cloudwatch_log_stream: ['A named sequence of log events inside a log group.', ['name', 'log_group_name'], ['arn']],
  aws_cloudwatch_log_metric_filter: ['Turns log events that match a pattern into a CloudWatch metric.', ['name', 'log_group_name', 'pattern', 'metric_transformation'], ['id']],
  aws_cloudwatch_metric_alarm: ['Watches one metric (or a metric math expression) and changes state when it crosses a threshold.', ['alarm_name', 'namespace', 'metric_name', 'dimensions', 'statistic', 'period', 'evaluation_periods', 'threshold', 'comparison_operator', 'treat_missing_data', 'alarm_actions', 'ok_actions'], ['arn', 'id']],
  aws_cloudwatch_composite_alarm: ['An alarm whose state is a rule over other alarms, such as ALARM(a) OR ALARM(b).', ['alarm_name', 'alarm_rule', 'alarm_actions', 'ok_actions', 'actions_suppressor'], ['arn', 'id']],
  aws_cloudwatch_dashboard: ['A CloudWatch dashboard defined by a JSON body of widgets.', ['dashboard_name', 'dashboard_body'], ['dashboard_arn']],
  aws_cloudwatch_event_rule: ['An EventBridge rule that matches events by pattern or runs on a schedule. The name dates from CloudWatch Events.', ['name', 'description', 'event_pattern', 'schedule_expression', 'state', 'event_bus_name'], ['arn', 'id']],
  aws_cloudwatch_event_target: ['Where an EventBridge rule sends matching events: SNS, Lambda, a log group, SQS and more.', ['rule', 'arn', 'target_id', 'input_transformer', 'role_arn', 'dead_letter_config'], []],
  aws_cloudwatch_log_resource_policy: ['A resource policy that lets AWS services such as EventBridge write to CloudWatch Logs.', ['policy_name', 'policy_document'], ['id', 'policy_scope']],
  aws_sns_topic: ['An SNS topic: a publish-subscribe channel for notifications.', ['name', 'kms_master_key_id', 'fifo_topic', 'delivery_policy'], ['arn', 'id', 'owner']],
  aws_sns_topic_policy: ['The resource policy that decides who may publish to or subscribe to a topic.', ['arn', 'policy'], ['owner']],
  aws_sns_topic_subscription: ['Subscribes an endpoint (email, SQS, Lambda, HTTPS) to a topic.', ['topic_arn', 'protocol', 'endpoint', 'filter_policy'], ['arn', 'pending_confirmation', 'confirmation_was_authenticated']],
  aws_iam_role: ['An IAM identity that trusted principals assume for temporary credentials.', ['name', 'name_prefix', 'assume_role_policy', 'max_session_duration', 'description'], ['arn', 'name', 'unique_id']],
  aws_iam_role_policy_attachment: ['Attaches a managed policy to a role.', ['role', 'policy_arn'], ['id']],
  aws_iam_instance_profile: ['The container that lets an EC2 instance use an IAM role.', ['name', 'name_prefix', 'role'], ['arn', 'id', 'unique_id']],
  aws_iam_policy: ['A customer managed IAM policy document.', ['name', 'name_prefix', 'description', 'policy'], ['arn', 'id', 'policy_id']],
  aws_ecs_cluster: ['A logical grouping of ECS services and tasks.', ['name', 'setting', 'configuration'], ['arn', 'id', 'name']],
  aws_ecs_task_definition: ['Describes the containers ECS should run.', ['family', 'requires_compatibilities', 'network_mode', 'cpu', 'memory', 'execution_role_arn', 'container_definitions'], ['arn', 'revision', 'family']],
  aws_ecs_service: ['Keeps a number of task copies running and registered with a load balancer.', ['name', 'cluster', 'task_definition', 'desired_count', 'launch_type', 'network_configuration', 'load_balancer'], ['id', 'name', 'cluster']],
  aws_eks_cluster: ['A managed Kubernetes control plane.', ['name', 'role_arn', 'version', 'vpc_config', 'access_config', 'encryption_config'], ['arn', 'endpoint', 'certificate_authority', 'identity', 'status']],
  aws_eks_node_group: ['A managed group of EC2 worker nodes for an EKS cluster.', ['cluster_name', 'node_group_name', 'node_role_arn', 'subnet_ids', 'instance_types', 'scaling_config'], ['arn', 'id', 'status', 'resources']],
  aws_ecr_repository: ['A private container image repository.', ['name', 'image_tag_mutability', 'image_scanning_configuration', 'encryption_configuration'], ['arn', 'repository_url', 'registry_id']],
  aws_ecr_lifecycle_policy: ['Rules that expire old or untagged images.', ['repository', 'policy'], ['repository', 'registry_id']],
  aws_ssm_parameter: ['A Parameter Store value (String, StringList or SecureString).', ['name', 'type', 'value', 'tier', 'description'], ['arn', 'version']],
  aws_db_subnet_group: ['Subnets across AZs that RDS may place databases into.', ['name', 'name_prefix', 'subnet_ids', 'description'], ['id', 'arn', 'name']],
  aws_db_instance: ['A single RDS database instance. The engine argument picks PostgreSQL, MySQL, MariaDB, Oracle or SQL Server.', ['engine', 'engine_version', 'instance_class', 'allocated_storage', 'username', 'manage_master_user_password', 'db_subnet_group_name', 'multi_az', 'storage_encrypted'], ['address', 'endpoint', 'port', 'arn', 'master_user_secret']],
  aws_rds_cluster: ['An Aurora cluster: shared storage plus cluster endpoints.', ['cluster_identifier', 'engine', 'engine_version', 'database_name', 'master_username', 'manage_master_user_password', 'db_subnet_group_name'], ['endpoint', 'reader_endpoint', 'arn', 'master_user_secret']],
  aws_rds_cluster_instance: ['A compute instance inside an Aurora cluster.', ['cluster_identifier', 'instance_class', 'engine', 'identifier'], ['endpoint', 'writer', 'arn']],
  aws_dynamodb_table: ['A DynamoDB table defined by its keys and capacity mode.', ['name', 'billing_mode', 'hash_key', 'range_key', 'attribute', 'point_in_time_recovery', 'server_side_encryption'], ['arn', 'id', 'stream_arn']],
  aws_elasticache_subnet_group: ['Subnets ElastiCache may use.', ['name', 'subnet_ids'], ['id']],
  aws_elasticache_replication_group: ['A Valkey or Redis OSS primary with replicas.', ['replication_group_id', 'engine', 'node_type', 'num_cache_clusters', 'automatic_failover_enabled', 'transit_encryption_enabled'], ['primary_endpoint_address', 'reader_endpoint_address', 'arn']],
  aws_memorydb_subnet_group: ['Subnets MemoryDB may use.', ['name', 'subnet_ids'], ['id', 'arn']],
  aws_memorydb_cluster: ['A durable in-memory database cluster.', ['name', 'acl_name', 'node_type', 'num_shards', 'num_replicas_per_shard', 'tls_enabled'], ['arn', 'cluster_endpoint', 'shards']],
  aws_s3_bucket: ['An S3 bucket. Versioning, encryption and lifecycle are separate resources since provider v4.', ['bucket', 'bucket_prefix', 'force_destroy', 'tags'], ['id', 'arn', 'bucket', 'bucket_regional_domain_name']],
  aws_s3_bucket_public_access_block: ['Blocks public ACLs and policies on a bucket.', ['bucket', 'block_public_acls', 'block_public_policy', 'ignore_public_acls', 'restrict_public_buckets'], ['id']],
  aws_s3_bucket_ownership_controls: ['Controls object ownership; BucketOwnerEnforced disables ACLs.', ['bucket', 'rule'], ['id']],
  aws_s3_bucket_versioning: ['Turns object versioning on or suspends it.', ['bucket', 'versioning_configuration'], ['id']],
  aws_s3_bucket_server_side_encryption_configuration: ['Default encryption for new objects in a bucket.', ['bucket', 'rule'], ['id']],
  aws_s3_bucket_lifecycle_configuration: ['Rules that transition or expire objects over time.', ['bucket', 'rule'], ['id']],
  aws_ebs_volume: ['A block storage volume in one AZ.', ['availability_zone', 'size', 'type', 'iops', 'throughput', 'encrypted', 'kms_key_id'], ['id', 'arn']],
  aws_volume_attachment: ['Attaches an EBS volume to an instance.', ['device_name', 'volume_id', 'instance_id'], ['id']],
  aws_efs_file_system: ['A managed NFS file system.', ['creation_token', 'encrypted', 'performance_mode', 'throughput_mode', 'lifecycle_policy'], ['id', 'arn', 'dns_name']],
  aws_efs_mount_target: ['An NFS endpoint for the file system inside one subnet.', ['file_system_id', 'subnet_id', 'security_groups'], ['id', 'dns_name', 'ip_address']],
  aws_fsx_lustre_file_system: ['A Lustre parallel file system.', ['storage_capacity', 'subnet_ids', 'deployment_type', 'per_unit_storage_throughput', 'security_group_ids'], ['id', 'arn', 'dns_name', 'mount_name']],
  aws_backup_vault: ['An encrypted container for recovery points.', ['name', 'kms_key_arn', 'force_destroy', 'tags'], ['arn', 'id', 'recovery_points']],
  aws_backup_plan: ['A backup plan: one or more rules that say when backups run, how long they are kept and where copies go.', ['name', 'rule', 'rule_name', 'schedule', 'schedule_expression_timezone', 'start_window', 'completion_window', 'lifecycle', 'copy_action', 'enable_continuous_backup'], ['id', 'arn', 'version']],
  aws_backup_selection: ['Which resources a backup plan protects, and the IAM role AWS Backup uses to reach them.', ['name', 'plan_id', 'iam_role_arn', 'resources', 'not_resources', 'selection_tag', 'condition'], ['id']],
  aws_backup_vault_lock_configuration: ['Vault Lock: minimum and maximum retention enforced on a vault, in governance or compliance mode.', ['backup_vault_name', 'min_retention_days', 'max_retention_days', 'changeable_for_days'], ['backup_vault_arn', 'backup_vault_name']],
  aws_backup_vault_policy: ['A resource policy on a vault, often used to deny deleting recovery points.', ['backup_vault_name', 'policy'], ['backup_vault_arn', 'id']],
  aws_backup_vault_notifications: ['Sends vault events (job, restore, copy and recovery point events) to an SNS topic.', ['backup_vault_name', 'sns_topic_arn', 'backup_vault_events'], ['backup_vault_arn', 'id']],
  aws_kms_key: ['A customer managed encryption key.', ['description', 'enable_key_rotation', 'deletion_window_in_days', 'policy'], ['arn', 'key_id']],
  aws_kms_alias: ['A friendly name for a KMS key.', ['name', 'target_key_id'], ['arn', 'target_key_arn']],
  'data.aws_availability_zones': ['Looks up the Availability Zones available in the current region.', ['state', 'filter'], ['names', 'zone_ids']],
  'data.aws_ami': ['Finds an AMI ID by filters, so you never hard-code AMI IDs.', ['most_recent', 'owners', 'filter'], ['id', 'name', 'architecture']],
  'data.aws_iam_policy_document': ['Builds IAM policy JSON from HCL blocks; validated at plan time.', ['statement'], ['json']],
  'data.aws_caller_identity': ['Returns the account ID and ARN of the credentials Terraform is using.', [], ['account_id', 'arn', 'user_id']],
  'data.aws_cloudfront_cache_policy': ['Looks up a CloudFront cache policy, such as the AWS managed ones.', ['name', 'id'], ['id', 'etag']],
  'data.aws_cloudfront_origin_request_policy': ['Looks up a CloudFront origin request policy.', ['name', 'id'], ['id', 'etag']],
  'data.archive_file': ['From the hashicorp/archive provider: zips a directory at plan time.', ['type', 'source_dir', 'output_path'], ['output_path', 'output_base64sha256']],
  aws_organizations_organization: ['Creates (or, after import, manages) the AWS Organization: feature set, enabled policy types and trusted service access.', ['feature_set', 'enabled_policy_types', 'aws_service_access_principals'], ['id', 'arn', 'roots', 'master_account_id', 'accounts', 'non_master_accounts']],
  'data.aws_organizations_organization': ['Reads the organization the credentials belong to, including its root ID and accounts. Creates nothing.', [], ['id', 'arn', 'roots', 'master_account_id', 'accounts']],
  aws_organizations_organizational_unit: ['An organizational unit (OU): a container for accounts and other OUs, used to apply policies to a group.', ['name', 'parent_id', 'tags'], ['id', 'arn', 'accounts']],
  aws_organizations_account: ['Creates a member account in the organization, or manages an imported one. parent_id decides which OU it sits in.', ['name', 'email', 'parent_id', 'role_name', 'iam_user_access_to_billing', 'close_on_deletion', 'tags'], ['id', 'arn', 'state', 'joined_method']],
  aws_organizations_policy: ['An organization policy. With type SERVICE_CONTROL_POLICY it is an SCP: a permission boundary for member accounts.', ['name', 'description', 'type', 'content', 'skip_destroy', 'tags'], ['id', 'arn']],
  aws_organizations_policy_attachment: ['Attaches an organization policy to the root, an OU or an account.', ['policy_id', 'target_id', 'skip_destroy'], []],
  aws_controltower_landing_zone: ['Creates the AWS Control Tower landing zone from a manifest JSON document and a landing zone version.', ['manifest_json', 'version', 'remediation_types', 'tags'], ['id', 'arn', 'drift_status', 'latest_available_version']],
  aws_controltower_baseline: ['Enables a Control Tower baseline on an OU. AWSControlTowerBaseline registers the OU and enrolls its accounts.', ['baseline_identifier', 'baseline_version', 'target_identifier', 'parameters'], ['arn', 'operaton_identifier']],
  aws_controltower_control: ['Enables one Control Tower control (strongly recommended or elective) on a registered OU.', ['control_identifier', 'target_identifier', 'parameters'], ['arn', 'id']],
  aws_servicecatalog_provisioned_product: ['Provisions a Service Catalog product. Here it provisions the Control Tower Account Factory product, which creates and enrolls an account.', ['name', 'product_name', 'provisioning_artifact_id', 'provisioning_parameters', 'path_id'], ['id', 'arn', 'outputs', 'status']],
  aws_iam_role_policy: ['An inline policy embedded in one IAM role.', ['name', 'role', 'policy'], ['id']],
};
function resDoc(t) { return t.startsWith('data.') ? docUrl(t) : docUrl(t); }

// Deeper notes for the Backup and Monitoring resources, shown in the Learn drawer:
// why it is needed, what it depends on, where it sits in AWS, common mistakes and a minimal example.
const RES_GUIDE = {
  aws_backup_vault: {
    why: 'Every recovery point AWS Backup creates is stored in a vault. The vault decides the encryption key and who may manage recovery points.',
    deps: 'Optionally a KMS key (kms_key_arn). Plans, selections, Vault Lock, vault policies and notifications all reference the vault by name.',
    arch: 'Regional. Recovery points for EBS, RDS, DynamoDB, EFS, S3 and more land here; copy_action can send copies to a vault in another Region or account.',
    mistakes: ['Expecting terraform destroy to delete a vault that still holds recovery points (it fails unless force_destroy is true).', 'Changing kms_key_arn later: it forces a new vault, and existing recovery points stay in the old one.'],
    example: 'resource "aws_backup_vault" "main" {\n  name        = "app-vault"\n  kms_key_arn = aws_kms_key.main.arn\n}',
  },
  aws_backup_plan: {
    why: 'The plan is the policy: when backups run, how long they are kept, whether they move to cold storage and where copies go.',
    deps: 'target_vault_name references the vault. A plan protects nothing until an aws_backup_selection points at it.',
    arch: 'AWS Backup starts a backup job for every selected resource at each scheduled time; each job produces a recovery point in the vault.',
    mistakes: ['Setting delete_after less than 90 days after cold_storage_after.', 'A start window under 60 minutes, or a completion window that is not at least 60 minutes longer than the start window.', 'Keeping continuous backups for more than 35 days.', 'Forgetting that schedule is evaluated in schedule_expression_timezone (UTC by default).'],
    example: 'resource "aws_backup_plan" "main" {\n  name = "daily"\n\n  rule {\n    rule_name         = "daily"\n    target_vault_name = aws_backup_vault.main.name\n    schedule          = "cron(0 18 * * ? *)"\n\n    lifecycle {\n      delete_after = 35\n    }\n  }\n}',
  },
  aws_backup_selection: {
    why: 'It tells a plan which resources to protect, by ARN, wildcard ARN pattern or tag, and which IAM role AWS Backup uses to reach them.',
    deps: 'plan_id references the plan; iam_role_arn references a role that trusts backup.amazonaws.com.',
    arch: 'Resources listed or tagged here become the targets of each scheduled backup job.',
    mistakes: ['Selecting by tag and forgetting to tag the resources.', 'Relying on tag or service selection for a resource type that is not opted in under AWS Backup settings for the Region.', 'Backing up S3 without versioning, or without the S3 backup policy on the role.'],
    example: 'resource "aws_backup_selection" "main" {\n  name         = "tagged"\n  plan_id      = aws_backup_plan.main.id\n  iam_role_arn = aws_iam_role.backup.arn\n\n  selection_tag {\n    type  = "STRINGEQUALS"\n    key   = "Backup"\n    value = "true"\n  }\n}',
  },
  aws_backup_vault_lock_configuration: {
    why: 'Vault Lock enforces retention limits so that recovery points cannot be deleted early, which protects backups from mistakes and ransomware.',
    deps: 'backup_vault_name references the vault. Backup rules targeting the vault must keep retention between the minimum and maximum.',
    arch: 'Governance mode (no changeable_for_days) can be removed by authorised users. Compliance mode becomes immutable when the grace period ends.',
    mistakes: ['Enabling compliance mode on a learning account: after the grace period nobody can remove it.', 'A backup rule whose retention falls outside min_retention_days to max_retention_days, which makes jobs fail.'],
    example: 'resource "aws_backup_vault_lock_configuration" "main" {\n  backup_vault_name  = aws_backup_vault.main.name\n  min_retention_days = 7\n  max_retention_days = 365\n}',
  },
  aws_backup_vault_policy: {
    why: 'A resource policy on the vault adds a second layer of protection on top of IAM, for example denying DeleteRecoveryPoint to everyone.',
    deps: 'backup_vault_name references the vault; the policy is usually built with data.aws_iam_policy_document.',
    arch: 'Evaluated together with IAM policies whenever someone calls the AWS Backup API against the vault.',
    mistakes: ['Denying deletion and then expecting force_destroy to empty the vault.'],
    example: 'resource "aws_backup_vault_policy" "main" {\n  backup_vault_name = aws_backup_vault.main.name\n  policy            = data.aws_iam_policy_document.backup_vault.json\n}',
  },
  aws_backup_vault_notifications: {
    why: 'Sends selected vault events straight to SNS without EventBridge.',
    deps: 'The vault, and an SNS topic whose policy lets backup.amazonaws.com publish.',
    arch: 'AWS Backup, then SNS, then subscribers. EventBridge sees more event types and can filter on details, so both routes are shown in this studio.',
    mistakes: ['Forgetting the SNS topic policy statement for backup.amazonaws.com.', 'Using a FIFO topic, which AWS Backup notifications do not support.'],
    example: 'resource "aws_backup_vault_notifications" "main" {\n  backup_vault_name   = aws_backup_vault.main.name\n  sns_topic_arn       = aws_sns_topic.alerts.arn\n  backup_vault_events = ["BACKUP_JOB_FAILED"]\n}',
  },
  aws_cloudwatch_log_group: {
    why: 'Logs are stored in log groups. Creating the group in Terraform lets you set retention and encryption instead of accepting "never expire".',
    deps: 'Optionally a KMS key whose key policy allows logs.<region>.amazonaws.com.',
    arch: 'Applications, Lambda, ECS and the CloudWatch agent write log streams into the group; metric filters and subscriptions read from it.',
    mistakes: ['Leaving retention unset, which keeps logs forever and grows cost.', 'Using a KMS key whose policy does not allow CloudWatch Logs, so creation fails.', 'Choosing INFREQUENT_ACCESS and then adding metric filters, which that class does not support.'],
    example: 'resource "aws_cloudwatch_log_group" "app" {\n  name              = "/aws/app/demo"\n  retention_in_days = 30\n}',
  },
  aws_cloudwatch_log_stream: {
    why: 'A stream is one sequence of events, usually one per instance, container or function version.',
    deps: 'log_group_name references the log group.',
    arch: 'Most writers create their own streams; create one in Terraform only when a writer expects it to exist.',
    mistakes: ['Using a colon in the stream name.'],
    example: 'resource "aws_cloudwatch_log_stream" "app" {\n  name           = "app"\n  log_group_name = aws_cloudwatch_log_group.app.name\n}',
  },
  aws_cloudwatch_log_metric_filter: {
    why: 'Turns text in logs, such as ERROR lines, into a number you can graph and alarm on.',
    deps: 'log_group_name references the log group. An alarm then references the metric by namespace and name.',
    arch: 'CloudWatch Logs, then the metric filter, then a CloudWatch metric, then an alarm, then SNS.',
    mistakes: ['Alarming on a filter metric with dimensions it never publishes.', 'Omitting default_value, so quiet periods have no data points.'],
    example: 'resource "aws_cloudwatch_log_metric_filter" "errors" {\n  name           = "errors"\n  log_group_name = aws_cloudwatch_log_group.app.name\n  pattern        = "ERROR"\n\n  metric_transformation {\n    name      = "ApplicationErrors"\n    namespace = "Application"\n    value     = "1"\n  }\n}',
  },
  aws_cloudwatch_metric_alarm: {
    why: 'An alarm watches a metric and acts when it crosses a threshold for a number of periods, for example notifying an SNS topic.',
    deps: 'The watched resource (through dimensions) and optionally an SNS topic in alarm_actions and ok_actions.',
    arch: 'Metric, then alarm (OK, ALARM or INSUFFICIENT_DATA), then actions such as SNS, Auto Scaling or EC2 actions.',
    mistakes: ['Missing dimensions, so the alarm watches a metric that never receives data.', 'Using Average for count metrics such as 5XX errors; Sum is usually right.', 'A period that is not 10, 20, 30 or a multiple of 60 seconds.'],
    example: 'resource "aws_cloudwatch_metric_alarm" "cpu" {\n  alarm_name          = "high-cpu"\n  namespace           = "AWS/EC2"\n  metric_name         = "CPUUtilization"\n  statistic           = "Average"\n  period              = 300\n  evaluation_periods  = 2\n  threshold           = 80\n  comparison_operator = "GreaterThanThreshold"\n\n  dimensions = {\n    InstanceId = aws_instance.main.id\n  }\n}',
  },
  aws_cloudwatch_composite_alarm: {
    why: 'Combines alarms with AND, OR and NOT so one notification represents a situation instead of many noisy alarms.',
    deps: 'alarm_rule references other alarms by name.',
    arch: 'Metric alarms, then the composite alarm, then its actions.',
    mistakes: ['Also sending notifications from every child alarm, which defeats the noise reduction.'],
    example: 'resource "aws_cloudwatch_composite_alarm" "any" {\n  alarm_name = "service-degraded"\n  alarm_rule = "ALARM(${aws_cloudwatch_metric_alarm.cpu.alarm_name}) OR ALARM(${aws_cloudwatch_metric_alarm.errors.alarm_name})"\n}',
  },
  aws_cloudwatch_dashboard: {
    why: 'A shared view of the metrics that matter, kept in code so every environment gets the same dashboard.',
    deps: 'Widgets reference resources (instance IDs, load balancer ARN suffixes, function names) through Terraform expressions.',
    arch: 'Reads metrics from CloudWatch; it stores no data of its own.',
    mistakes: ['Hard-coding instance IDs in dashboard JSON instead of Terraform references.', 'Writing the body as a JSON string with manual escaping instead of jsonencode().'],
    example: 'resource "aws_cloudwatch_dashboard" "main" {\n  dashboard_name = "app"\n  dashboard_body = jsonencode({\n    widgets = [{\n      type       = "metric"\n      width      = 12\n      height     = 6\n      properties = {\n        region  = var.aws_region\n        metrics = [["AWS/EC2", "CPUUtilization", "InstanceId", aws_instance.main.id]]\n      }\n    }]\n  })\n}',
  },
  aws_cloudwatch_event_rule: {
    why: 'EventBridge rules react to events from AWS services, such as a failed backup job or an instance stopping, or run on a schedule.',
    deps: 'Nothing required. Targets are separate aws_cloudwatch_event_target resources.',
    arch: 'AWS service event, then the default event bus, then the rule pattern match, then targets. The Terraform name comes from CloudWatch Events, which EventBridge replaced.',
    mistakes: ['Using the deprecated is_enabled argument instead of state.', 'Writing event_pattern keys that do not match the event exactly, such as detail_type instead of "detail-type".'],
    example: 'resource "aws_cloudwatch_event_rule" "backup_failed" {\n  name  = "backup-failed"\n  state = "ENABLED"\n\n  event_pattern = jsonencode({\n    source        = ["aws.backup"]\n    "detail-type" = ["Backup Job State Change"]\n    detail        = { state = ["FAILED"] }\n  })\n}',
  },
  aws_cloudwatch_event_target: {
    why: 'Connects a rule to where matching events go.',
    deps: 'rule references the rule name; arn references the target. The target also needs permission: an SNS topic policy, a Lambda permission or a CloudWatch Logs resource policy.',
    arch: 'Rule, then target (SNS, Lambda, SQS, CloudWatch Logs and more).',
    mistakes: ['Forgetting the target permission, so events are dropped silently.'],
    example: 'resource "aws_cloudwatch_event_target" "sns" {\n  rule = aws_cloudwatch_event_rule.backup_failed.name\n  arn  = aws_sns_topic.alerts.arn\n}',
  },
  aws_cloudwatch_log_resource_policy: {
    why: 'Lets AWS services such as EventBridge write into CloudWatch Logs in your account.',
    deps: 'A policy document naming the service principals and the log group ARNs.',
    arch: 'EventBridge, then the log group. The policy is account-wide per Region and is limited to a small number per Region.',
    mistakes: ['Creating many policies instead of one broader one, and hitting the per-Region limit.'],
    example: 'resource "aws_cloudwatch_log_resource_policy" "events" {\n  policy_name     = "events-to-logs"\n  policy_document = data.aws_iam_policy_document.events_to_logs.json\n}',
  },
  aws_sns_topic: {
    why: 'One place for alarms and events to publish to; subscribers such as email, chat or Lambda receive every message.',
    deps: 'None. Publishers need permission through the topic policy.',
    arch: 'CloudWatch alarms, EventBridge and AWS Backup, then SNS, then subscriptions.',
    mistakes: ['Encrypting the topic with a KMS key whose policy does not let the publishing services use it.'],
    example: 'resource "aws_sns_topic" "alerts" {\n  name = "alerts"\n}',
  },
  aws_sns_topic_policy: {
    why: 'Lets only specific AWS services publish, and replaces the default topic policy.',
    deps: 'The topic ARN and a policy document with one statement per publishing service.',
    arch: 'Checked on every Publish call to the topic.',
    mistakes: ['Granting sns:Publish to "*" without a condition.', 'Forgetting a statement for one of the publishers, so its messages are rejected.'],
    example: 'resource "aws_sns_topic_policy" "alerts" {\n  arn    = aws_sns_topic.alerts.arn\n  policy = data.aws_iam_policy_document.sns_alerts.json\n}',
  },
  aws_sns_topic_subscription: {
    why: 'Delivers topic messages to an endpoint such as an email address.',
    deps: 'topic_arn references the topic.',
    arch: 'SNS, then the endpoint. Email subscriptions stay pending until the recipient confirms.',
    mistakes: ['Expecting email to arrive before the confirmation link is clicked.', 'Committing personal email addresses to shared code; pass them as variables.'],
    example: 'resource "aws_sns_topic_subscription" "email" {\n  topic_arn = aws_sns_topic.alerts.arn\n  protocol  = "email"\n  endpoint  = var.alerts_email\n}',
  },
  aws_organizations_organization: {
    why: 'Everything in a landing zone hangs off the organization: its root is the parent of every OU, and only an organization with all features can use SCPs, trusted access and Control Tower.',
    deps: 'Nothing. Run it with management account credentials. OUs, accounts and policy attachments reference roots[0].id.',
    arch: 'Global (not Regional). One organization per management account; the management account pays for and administers every member account.',
    mistakes: ['Destroying it by accident: keep prevent_destroy on.', 'Creating it with CONSOLIDATED_BILLING and later needing SCPs or Control Tower.', 'Listing only some trusted services when another tool (such as Control Tower) also enables them, so every plan tries to remove theirs.'],
    example: 'resource "aws_organizations_organization" "this" {\n  feature_set          = "ALL"\n  enabled_policy_types = ["SERVICE_CONTROL_POLICY"]\n}',
  },
  aws_organizations_organizational_unit: {
    why: 'OUs group accounts with the same governance needs, so a policy attached once applies to every account below.',
    deps: 'parent_id is the root ID or another OU\'s id. Referencing the parent resource makes Terraform create parents first.',
    arch: 'Up to five levels of OUs under the root. Policies attached to an OU are inherited by its child OUs and accounts.',
    mistakes: ['Modelling the org chart instead of security and operational boundaries.', 'Hard-coding ou-xxxx IDs instead of referencing the resource.', 'Deleting an OU that still contains accounts (AWS refuses).'],
    example: 'resource "aws_organizations_organizational_unit" "workloads" {\n  name      = "Workloads"\n  parent_id = aws_organizations_organization.this.roots[0].id\n}',
  },
  aws_organizations_account: {
    why: 'Each account is a hard isolation boundary for resources, quotas, billing and blast radius. This resource creates one, or manages an imported one.',
    deps: 'parent_id references the target OU (or the root). The email must be unique across all of AWS.',
    arch: 'Organizations creates the account with an admin role (role_name) trusted by the management account. Moving the account is a change to parent_id.',
    mistakes: ['Reusing an email address already tied to another AWS account.', 'Expecting terraform destroy to delete the account: by default it only leaves the organization; close_on_deletion closes it, subject to AWS closure quotas.', 'Setting role_name on an imported account without ignore_changes, causing a permanent diff.'],
    example: 'resource "aws_organizations_account" "payments_prod" {\n  name      = "payments-prod"\n  email     = var.payments_prod_email\n  parent_id = aws_organizations_organizational_unit.production.id\n\n  lifecycle {\n    ignore_changes = [role_name]\n  }\n}',
  },
  aws_organizations_policy: {
    why: 'An SCP sets the maximum permissions for every IAM user and role in the accounts it applies to, including the account root user. It never grants anything.',
    deps: 'The SERVICE_CONTROL_POLICY type must be enabled on the root (enabled_policy_types). Nothing applies until an attachment exists.',
    arch: 'Evaluated on every request from a member account, together with IAM policies. The management account is never restricted by SCPs.',
    mistakes: ['Expecting an Allow statement in an SCP to grant access.', 'Exceeding 5,120 characters.', 'Attaching a deny-by-default SCP to the root without testing it on a sandbox OU first.'],
    example: 'resource "aws_organizations_policy" "deny_leave" {\n  name = "deny-leave-organization"\n  type = "SERVICE_CONTROL_POLICY"\n\n  content = jsonencode({\n    Version = "2012-10-17"\n    Statement = [{\n      Effect   = "Deny"\n      Action   = "organizations:LeaveOrganization"\n      Resource = "*"\n    }]\n  })\n}',
  },
  aws_organizations_policy_attachment: {
    why: 'It is the attachment, not the policy, that makes an SCP take effect on a root, OU or account.',
    deps: 'policy_id references the policy; target_id references the root, an OU or an account.',
    arch: 'An SCP attached to an OU applies to every account below it. A target can have up to five SCPs, including the default FullAWSAccess.',
    mistakes: ['Hitting the five-SCPs-per-target quota (Control Tower attaches its own SCPs to registered OUs).', 'Detaching FullAWSAccess without another Allow, which denies everything.'],
    example: 'resource "aws_organizations_policy_attachment" "deny_leave_workloads" {\n  policy_id = aws_organizations_policy.deny_leave.id\n  target_id = aws_organizations_organizational_unit.workloads.id\n}',
  },
  aws_controltower_landing_zone: {
    why: 'It asks AWS Control Tower to set up (or update) the landing zone: centralized logging, security roles, AWS Config and IAM Identity Center, described by a manifest.',
    deps: 'An organization with all features, the Log Archive and Audit accounts in one OU directly under the root, and the Control Tower service roles in /service-role/.',
    arch: 'Created in the home Region (the provider region). Control Tower then deploys StackSets, trails and SCPs it owns; Terraform tracks only the landing zone object.',
    mistakes: ['Using a manifest format from another landing zone version.', 'Leaving the home Region out of governedRegions.', 'Trying to manage the resources Control Tower creates (its trail, buckets or SCPs) with Terraform as well.'],
    example: 'resource "aws_controltower_landing_zone" "this" {\n  version = "4.0"\n  manifest_json = jsonencode({\n    governedRegions = ["ap-southeast-1"]\n    # centralizedLogging, config, securityRoles, accessManagement, backup\n  })\n}',
  },
  aws_controltower_baseline: {
    why: 'Enabling AWSControlTowerBaseline on an OU registers it with Control Tower and enrolls the accounts in it, so controls and Account Factory can target it.',
    deps: 'The landing zone must exist. A nested OU needs its parent registered first. With IAM Identity Center on, pass IdentityCenterEnabledBaselineArn.',
    arch: 'One baseline per OU. The baseline version must match the landing zone version (5.0 for landing zone 4.0).',
    mistakes: ['Registering the OU that holds the Log Archive and Audit accounts again.', 'Using a baseline version the landing zone does not support.', 'Expecting accounts without the AWSControlTowerExecution role to enroll.'],
    example: 'resource "aws_controltower_baseline" "workloads" {\n  baseline_identifier = "arn:aws:controltower:ap-southeast-1::baseline/17BSJV3IGJ2QSGA2"\n  baseline_version    = "5.0"\n  target_identifier   = aws_organizations_organizational_unit.workloads.arn\n}',
  },
  aws_controltower_control: {
    why: 'Turns on one Control Tower control for an OU. Control Tower then deploys the SCP, AWS Config rule or CloudFormation hook behind it.',
    deps: 'target_identifier is the ARN (not the ID) of a registered OU. Mandatory controls cannot be managed; strongly recommended and elective ones can.',
    arch: 'Controls are owned by Control Tower. A preventive control is an SCP that Control Tower attaches; a detective control is an AWS Config rule in every enrolled account.',
    mistakes: ['Passing the OU id instead of its arn.', 'Targeting an OU that is not registered.', 'Writing a customer SCP that duplicates a control you could enable instead.'],
    example: 'resource "aws_controltower_control" "root_keys" {\n  control_identifier = "arn:aws:controltower:ap-southeast-1::control/AWS-GR_RESTRICT_ROOT_USER_ACCESS_KEYS"\n  target_identifier  = aws_organizations_organizational_unit.workloads.arn\n}',
  },
  aws_servicecatalog_provisioned_product: {
    why: 'Control Tower Account Factory is a Service Catalog product. Provisioning it creates an account, places it in a registered OU and enrolls it in one step.',
    deps: 'A landing zone, a registered target OU, the Account Factory provisioning artifact ID, and a caller that is a principal of the Account Factory portfolio.',
    arch: 'Service Catalog runs the product; Control Tower creates the account and applies the OU baseline. Terraform tracks the provisioned product.',
    mistakes: ['Using the old OU_NAME format for ManagedOrganizationalUnit: it is now "Name (ou-xxxx)".', 'Forgetting that the target OU must already be registered with Control Tower.', 'Managing the same account with aws_organizations_account as well.'],
    example: 'resource "aws_servicecatalog_provisioned_product" "app" {\n  name                     = "app-prod"\n  product_name             = "AWS Control Tower Account Factory"\n  provisioning_artifact_id = var.account_factory_provisioning_artifact_id\n\n  provisioning_parameters {\n    key   = "AccountName"\n    value = "app-prod"\n  }\n}',
  },
};

// Concept guides for the Backup and Monitoring categories, shown in the Learn tab.
const SERVICE_GUIDES = [
  { svc: 'backup', title: 'AWS Backup', items: [
    ['Backup vault', 'The encrypted container where recovery points are stored. Each vault has one KMS key.'],
    ['Backup plan', 'A named policy made of one or more rules. The plan does nothing until a selection points at it.'],
    ['Backup rule', 'Schedule, start and completion windows, lifecycle (cold storage and deletion), copy actions and continuous backup.'],
    ['Backup selection', 'The resources a plan protects: ARNs, wildcard ARN patterns or tags, plus the IAM role AWS Backup assumes.'],
    ['Backup job', 'One backup of one resource at one time. States include CREATED, RUNNING, COMPLETED, FAILED, ABORTED and EXPIRED.'],
    ['Recovery point', 'The result of a successful job: a snapshot or backup you restore from. Restores are started on demand, not by Terraform.'],
    ['Backup IAM role', 'A role that trusts backup.amazonaws.com. AWSBackupServiceRolePolicyForBackup and ...ForRestores cover most services; S3 needs its own policies.'],
    ['Vault Lock', 'Enforced minimum and maximum retention. Governance mode can be removed; compliance mode becomes immutable after the grace period.'],
    ['Retention', 'delete_after in the rule lifecycle. With cold storage, retention must be at least 90 days longer than the cold storage delay.'],
    ['Cross-Region backup', 'A copy_action to a vault in another Region protects against a Regional outage.'],
    ['Cross-account backup', 'A copy_action to a vault in another account (inside AWS Organizations) protects against a compromised account.'],
    ['Region opt-in settings', 'aws_backup_region_settings turns resource types on for tag and service selections. It is account-wide, so manage it once per account.'],
  ] },
  { svc: 'cloudwatch', title: 'Amazon CloudWatch', items: [
    ['Metrics', 'Time-ordered numbers identified by namespace, metric name and dimensions, such as AWS/EC2 CPUUtilization for one InstanceId.'],
    ['Logs', 'Text events from applications and AWS services, stored in CloudWatch Logs.'],
    ['Log groups', 'Containers for log streams, with retention, log class and encryption.'],
    ['Log streams', 'One sequence of events inside a group, usually per instance, container or function.'],
    ['Alarms', 'Watch a metric and change state (OK, ALARM, INSUFFICIENT_DATA) when a threshold is crossed; actions run on state changes.'],
    ['Metric filters', 'Turn matching log lines into a metric so you can alarm on log content.'],
    ['Dashboards', 'Widgets that graph metrics. Build the JSON body with jsonencode() and Terraform references.'],
    ['Composite alarms', 'Combine alarms with AND, OR and NOT to reduce noise.'],
    ['EventBridge integration', 'Rules match service events, such as Backup Job State Change, and send them to targets. Terraform still names these resources aws_cloudwatch_event_*.'],
    ['SNS integration', 'Alarms, EventBridge and AWS Backup publish to a topic; subscribers receive the notification.'],
    ['Observability', 'Metrics say something is wrong, logs say why, and events say what changed. Good monitoring connects all three to someone who can act.'],
  ] },
];

// Learn AWS Landing Zones. reg lists provider types (linked to the Registry); "none" topics say so explicitly.
const AWSDOC = 'https://docs.aws.amazon.com/';
const LZ_TOPICS = [
  { t: 'What is a Landing Zone?', concept: 'A landing zone is a pre-configured, secure, multi-account AWS environment: an organization, a set of OUs, core accounts for security and logging, and guardrails, ready for workloads to land in.', purpose: 'Teams get new accounts quickly while security, logging and cost controls are already in place.', arch: 'AWS Organizations at the base, OUs for Security, Infrastructure and Workloads, core accounts, then policies (SCPs or Control Tower controls) applied by OU.', tf: 'There is no single "landing zone" resource in plain Organizations. Terraform builds it from aws_organizations_* resources; with Control Tower, aws_controltower_landing_zone asks Control Tower to build its part.', example: 'Root -> Security OU (log-archive, audit) -> Workloads OU -> Production / Non-Production OUs -> application accounts.', mistakes: ['Treating a landing zone as one product to install, instead of an architecture you operate.', 'Putting workloads in the management account.'], aws: AWSDOC + 'controltower/latest/userguide/aws-multi-account-landing-zone.html', reg: ['aws_organizations_organization', 'aws_controltower_landing_zone'] },
  { t: 'AWS Organizations', concept: 'A service that groups AWS accounts under one management account, with consolidated billing and, with all features, organization policies such as SCPs.', purpose: 'Central account creation, billing and governance for many accounts.', arch: 'One organization, one root, OUs below it, member accounts in OUs. The management account owns the organization.', tf: 'aws_organizations_organization creates or manages it; data.aws_organizations_organization reads an existing one.', example: 'resource "aws_organizations_organization" "this" {\n  feature_set = "ALL"\n}', mistakes: ['Creating it with CONSOLIDATED_BILLING only, which rules out SCPs and Control Tower.', 'Destroying it from Terraform: keep prevent_destroy.'], aws: AWSDOC + 'organizations/latest/userguide/orgs_introduction.html', reg: ['aws_organizations_organization', 'data.aws_organizations_organization'] },
  { t: 'Management Account', concept: 'The account that created the organization. It pays the bills and can create, invite and remove member accounts.', purpose: 'Organization administration only. AWS recommends keeping workloads out of it.', arch: 'Always sits in the root. SCPs never restrict it, so its access must be tightly controlled with IAM.', tf: 'Not a resource you create: Terraform runs with its credentials. aws_organizations_organization exposes master_account_id.', example: 'output "management_account_id" {\n  value = aws_organizations_organization.this.master_account_id\n}', mistakes: ['Expecting an SCP on the root to restrict the management account.', 'Running application resources in it.'], aws: AWSDOC + 'organizations/latest/userguide/orgs_best-practices_mgmt-acct.html', reg: ['aws_organizations_organization'] },
  { t: 'Organizational Units', concept: 'Containers for accounts and other OUs, up to five levels deep under the root.', purpose: 'Apply policies and governance to groups of accounts with the same needs.', arch: 'Policies attached to an OU are inherited by every OU and account below it.', tf: 'aws_organizations_organizational_unit, with parent_id referencing the root or the parent OU.', example: 'resource "aws_organizations_organizational_unit" "production" {\n  name      = "Production"\n  parent_id = aws_organizations_organizational_unit.workloads.id\n}', mistakes: ['Mirroring the company org chart instead of governance boundaries.', 'Hard-coding ou- IDs.'], aws: AWSDOC + 'organizations/latest/userguide/orgs_manage_ous.html', reg: ['aws_organizations_organizational_unit'] },
  { t: 'Multi-Account Strategy', concept: 'Using separate AWS accounts as the main isolation boundary between workloads, environments and teams.', purpose: 'Limits blast radius, separates billing and quotas, and makes access boundaries simple.', arch: 'Core accounts (log archive, security, network, shared services) plus workload accounts per application and environment.', tf: 'One aws_organizations_account per account; parent_id places it in its OU.', example: 'payments-prod in Production, payments-nonprod in Non-Production, sandbox-dev in Sandbox.', mistakes: ['One shared account for every environment.', 'Hundreds of accounts without an OU structure to govern them.'], aws: AWSDOC + 'whitepapers/latest/organizing-your-aws-environment/benefits-of-using-multiple-aws-accounts.html', reg: ['aws_organizations_account'] },
  { t: 'AWS Control Tower', concept: 'A managed service that sets up and governs a landing zone on top of AWS Organizations, using blueprints, controls and Account Factory.', purpose: 'A governed multi-account baseline maintained by AWS, with drift detection and a control library.', arch: 'Control Tower owns its CloudTrail trail, AWS Config setup, IAM Identity Center integration, StackSets and SCPs. It is set up in a home Region and governs selected Regions.', tf: 'aws_controltower_landing_zone (setup), aws_controltower_baseline (OU registration) and aws_controltower_control (controls). Control Tower-owned child resources are not Terraform resources.', example: 'resource "aws_controltower_landing_zone" "this" {\n  version       = "4.0"\n  manifest_json = jsonencode({ ... })\n}', mistakes: ['Managing Control Tower-owned resources with Terraform too.', 'Assuming every console action has a Terraform resource.'], aws: AWSDOC + 'controltower/latest/userguide/what-is-control-tower.html', reg: ['aws_controltower_landing_zone', 'aws_controltower_baseline', 'aws_controltower_control'] },
  { t: 'Account Factory', concept: 'Control Tower\'s account vending: a Service Catalog product that creates an account, places it in a registered OU and enrolls it.', purpose: 'Consistent, governed account creation.', arch: 'Service Catalog provisions the "AWS Control Tower Account Factory" product; Control Tower creates and baselines the account.', tf: 'aws_servicecatalog_provisioned_product. For a full GitOps pipeline, AWS publishes Account Factory for Terraform (AFT) as the aws-ia/control_tower_account_factory module.', example: 'provisioning_parameters {\n  key   = "ManagedOrganizationalUnit"\n  value = "Production (ou-ab12-cdef3456)"\n}', mistakes: ['Targeting an unregistered OU.', 'Also creating the same account with aws_organizations_account.'], aws: AWSDOC + 'controltower/latest/userguide/account-factory.html', reg: ['aws_servicecatalog_provisioned_product'] },
  { t: 'Account Enrollment', concept: 'Bringing an existing account under Control Tower governance.', purpose: 'Apply the OU baseline and controls to accounts created outside Account Factory.', arch: 'Registering an OU with AWSControlTowerBaseline enrolls its accounts. Each account needs the AWSControlTowerExecution role trusted by the management account.', tf: 'aws_controltower_baseline on the OU. Accounts created by aws_organizations_account get that role when role_name = "AWSControlTowerExecution".', example: 'resource "aws_controltower_baseline" "workloads" {\n  target_identifier = aws_organizations_organizational_unit.workloads.arn\n  # baseline_identifier, baseline_version\n}', mistakes: ['Accounts with an existing AWS Config recorder fail enrollment until it is removed.', 'Expecting to enroll an existing account as the log archive or audit account after setup.'], aws: AWSDOC + 'controltower/latest/userguide/enroll-account.html', reg: ['aws_controltower_baseline'] },
  { t: 'Service Control Policies', concept: 'Organization policies that set the maximum permissions available to IAM users and roles in member accounts.', purpose: 'Guardrails that hold no matter what IAM policies an account writes.', arch: 'Evaluated alongside IAM. An action must be allowed by every SCP from the root down to the account and by IAM.', tf: 'aws_organizations_policy (type SERVICE_CONTROL_POLICY) plus aws_organizations_policy_attachment.', example: 'content = jsonencode({\n  Version   = "2012-10-17"\n  Statement = [{ Effect = "Deny", Action = "organizations:LeaveOrganization", Resource = "*" }]\n})', mistakes: ['Thinking an SCP grants access.', 'Forgetting that SCPs do not affect the management account.'], aws: AWSDOC + 'organizations/latest/userguide/orgs_manage_policies_scps.html', reg: ['aws_organizations_policy', 'aws_organizations_policy_attachment'] },
  { t: 'SCP Inheritance', concept: 'An SCP attached to the root or an OU applies to every OU and account below it. Access needs an Allow at every level and no Deny at any level.', purpose: 'Attach a policy once and cover a whole branch of the organization.', arch: 'Root -> OU -> child OU -> account. FullAWSAccess is attached everywhere by default, so most SCPs are deny lists.', tf: 'Choose target_id: local root ID, an OU id or an account id.', example: 'An SCP on Workloads applies to Production, Non-Production and every account in them.', mistakes: ['Detaching FullAWSAccess from an OU, which denies everything below it.', 'The five-SCPs-per-target quota.'], aws: AWSDOC + 'organizations/latest/userguide/orgs_manage_policies_inheritance_auth.html', reg: ['aws_organizations_policy_attachment'] },
  { t: 'Centralized Logging', concept: 'Sending CloudTrail and AWS Config logs from every account to a dedicated log archive account.', purpose: 'Logs survive even if a workload account is compromised, and auditors have one place to look.', arch: 'An organization trail writes to an S3 bucket in the log archive account. Control Tower sets this up from the centralizedLogging manifest section.', tf: 'With Control Tower: the log archive account ID in the landing zone manifest. Without it: aws_cloudtrail with is_organization_trail and an S3 bucket in the log account (not generated here).', example: 'centralizedLogging = {\n  accountId = aws_organizations_account.log_archive.id\n  enabled   = true\n}', mistakes: ['Letting workload admins delete logs: protect them with SCPs or controls.', 'Short retention for compliance logs.'], aws: AWSDOC + 'prescriptive-guidance/latest/security-reference-architecture/log-archive.html', reg: ['aws_controltower_landing_zone', 'aws_organizations_account'] },
  { t: 'Security Account', concept: 'A dedicated account (called Audit in Control Tower) for security tooling and cross-account security access.', purpose: 'Delegated administrator for GuardDuty, Security Hub and similar services, separate from workloads.', arch: 'Control Tower deploys read-only and admin cross-account roles from this account (securityRoles).', tf: 'An aws_organizations_account; with Control Tower its ID goes into securityRoles.accountId and config.accountId.', example: 'securityRoles = {\n  enabled   = true\n  accountId = aws_organizations_account.audit.id\n}', mistakes: ['Running workloads in the security account.', 'Giving many people access to it.'], aws: AWSDOC + 'prescriptive-guidance/latest/security-reference-architecture/security-tooling.html', reg: ['aws_organizations_account'] },
  { t: 'Network Account', concept: 'An account that owns shared networking: Transit Gateway, VPN, Direct Connect and shared VPCs.', purpose: 'One team manages connectivity; workload accounts attach to it.', arch: 'Resources are shared to workload accounts with AWS RAM, or connected through Transit Gateway attachments.', tf: 'The account is an aws_organizations_account. Network resources are deployed into it by a separate configuration whose provider assumes a role in that account.', example: 'Transit Gateway in the network account, shared with RAM to Production and Non-Production.', mistakes: ['Creating cross-account resources from the management account without assume_role.'], aws: AWSDOC + 'prescriptive-guidance/latest/security-reference-architecture/network.html', reg: ['aws_organizations_account'] },
  { t: 'Shared Services', concept: 'An account for tooling used by many workloads: CI/CD, directory services, monitoring, backup administration.', purpose: 'Keep shared tools out of individual workload accounts.', arch: 'Workload accounts reach shared services through networking and cross-account IAM roles.', tf: 'An aws_organizations_account in the Infrastructure OU.', example: 'Central CloudWatch dashboards and AWS Backup policies managed from shared-services.', mistakes: ['Letting shared services become a dumping ground for workloads.'], aws: AWSDOC + 'prescriptive-guidance/latest/security-reference-architecture/shared-services.html', reg: ['aws_organizations_account'] },
  { t: 'Production / Non-Production Separation', concept: 'Separate OUs and accounts for production and non-production environments.', purpose: 'Stricter guardrails and access for production without slowing down development.', arch: 'Workloads OU with Production and Non-Production child OUs; different SCPs or controls on each.', tf: 'Two aws_organizations_organizational_unit resources with parent_id pointing at Workloads, and separate policy attachments.', example: 'Region restriction on both, plus deny-delete-without-MFA only on Production.', mistakes: ['Using tags alone to separate environments inside one account.'], aws: AWSDOC + 'whitepapers/latest/organizing-your-aws-environment/recommended-ous-and-accounts.html', reg: ['aws_organizations_organizational_unit'] },
  { t: 'Landing Zone Governance', concept: 'The combination of preventive guardrails (SCPs, preventive controls), detective guardrails (AWS Config rules) and processes for change.', purpose: 'Keep every account inside agreed boundaries as the organization grows.', arch: 'Customer SCPs: you write and attach them. Control Tower SCP-based controls: Control Tower owns and attaches them. AWS Config-based controls: detective rules that report but do not block. Proactive controls: CloudFormation hooks.', tf: 'Customer SCPs: aws_organizations_policy. Control Tower controls of any kind: aws_controltower_control with the control identifier.', example: 'AWS-GR_RESTRICT_ROOT_USER_ACCESS_KEYS (preventive, SCP) and AWS-GR_ENCRYPTED_VOLUMES (detective, AWS Config rule).', mistakes: ['Treating detective controls as if they block actions.', 'Duplicating a Control Tower control with a hand-written SCP.'], aws: AWSDOC + 'controltower/latest/controlreference/controls.html', reg: ['aws_organizations_policy', 'aws_controltower_control'] },
  { t: 'Terraform Landing Zone Automation', concept: 'Managing the organization, OUs, accounts and policies as code, reviewed in pull requests and applied by a pipeline.', purpose: 'Repeatable, auditable changes to the most sensitive part of AWS.', arch: 'One configuration in the management account (or a delegated account) for the organization; separate configurations per account for what runs inside them.', tf: 'Plain aws_organizations_* resources (this studio), Control Tower resources where supported, import blocks for existing accounts, and AFT for account vending at scale.', example: 'import {\n  to = aws_organizations_account.existing_prod\n  id = "123456789012"\n}', mistakes: ['Keeping organization state in a local file: use an encrypted remote backend with locking.', 'Applying organization changes without reading the plan.'], aws: AWSDOC + 'controltower/latest/userguide/taf-account-provisioning.html', reg: ['aws_organizations_account', 'aws_organizations_organizational_unit'] },
];

const TOPICS = [
  ['Beginner', 'Terraform', 'A tool that reads .tf files describing the infrastructure you want, compares that with what exists, and makes the changes. You describe the end state; Terraform works out the steps.', ''],
  ['Beginner', 'Providers', 'Plugins that teach Terraform how to talk to an API. hashicorp/aws translates resources into AWS API calls. Pin a version range so upgrades are deliberate.', 'required_providers {\n  aws = {\n    source  = "hashicorp/aws"\n    version = "~> 6.0"\n  }\n}'],
  ['Beginner', 'Resources', 'The things Terraform creates and manages. The first label is the type (from the provider), the second is your local name. Together they form an address like aws_vpc.main.', 'resource "aws_vpc" "main" {\n  cidr_block = "10.0.0.0/16"\n}'],
  ['Beginner', 'Variables', 'Inputs to your configuration, with a type, description and optional default and validation. Set them in terraform.tfvars, with -var, or TF_VAR_ environment variables.', 'variable "vpc_cidr" {\n  type    = string\n  default = "10.0.0.0/16"\n}'],
  ['Beginner', 'Outputs', 'Values Terraform prints after apply and exposes to other configurations, such as an endpoint or ID.', 'output "vpc_id" {\n  value = aws_vpc.main.id\n}'],
  ['Beginner', 'Data sources', 'Read-only lookups of things that already exist or are computed, such as the latest AMI or your account ID. They never create anything.', 'data "aws_caller_identity" "current" {}'],
  ['Beginner', 'Terraform state', 'A JSON record mapping each resource address to a real object ID. Terraform diffs config against state to plan. State can contain secrets, so keep it in an encrypted remote backend, never in Git.', ''],
  ['Beginner', 'terraform init', 'Downloads providers and modules and configures the backend. Run it first, and again whenever providers, modules or backend settings change.', 'terraform init'],
  ['Beginner', 'terraform plan', 'Shows what would change without changing anything. Read it every time: "+" create, "~" update in place, "-/+" replace, "-" destroy.', 'terraform plan -out=tfplan'],
  ['Beginner', 'terraform apply', 'Makes the planned changes. Applying a saved plan file guarantees you get exactly what you reviewed.', 'terraform apply tfplan'],
  ['Beginner', 'terraform destroy', 'Deletes everything in the state. Deletion protection on databases or load balancers will block it until you turn protection off.', 'terraform destroy'],
  ['Intermediate', 'Modules', 'A folder of .tf files with inputs and outputs that you call from another configuration. Every configuration is a module; the one you run is the root module.', 'module "vpc" {\n  source = "terraform-aws-modules/vpc/aws"\n  # version = "<pin from the Registry>"\n  name = "demo"\n  cidr = "10.0.0.0/16"\n}'],
  ['Intermediate', 'Locals', 'Named expressions computed once and reused, like a naming prefix or a merged tag map. Unlike variables, callers cannot override them.', 'locals {\n  name_prefix = "${var.project_name}-${var.environment}"\n}'],
  ['Intermediate', 'for_each', 'Creates one instance per map key or set element, addressed by key (aws_subnet.private["private-a"]). Removing one key only affects that instance, which is why it beats count for most collections.', 'resource "aws_subnet" "private" {\n  for_each   = var.private_subnets\n  cidr_block = each.value.cidr_block\n  vpc_id     = aws_vpc.main.id\n}'],
  ['Intermediate', 'count', 'Creates N numbered copies (aws_rds_cluster_instance.main[0]). Good for identical replicas or on/off toggles; poor for lists that change order, because indexes shift.', 'count = var.create_bastion ? 1 : 0'],
  ['Intermediate', 'dynamic blocks', 'Generate repeated nested blocks from a collection. Use sparingly: they make code harder to read.', 'dynamic "attribute" {\n  for_each = var.range_key == null ? [] : [var.range_key]\n  content {\n    name = attribute.value\n    type = "S"\n  }\n}'],
  ['Intermediate', 'depends_on', 'Forces ordering when Terraform cannot see a dependency through references. Most dependencies are implicit: referencing aws_vpc.main.id already makes the subnet wait for the VPC.', 'depends_on = [aws_internet_gateway.main]'],
  ['Intermediate', 'lifecycle', 'Changes how Terraform replaces or updates a resource: create_before_destroy, prevent_destroy, ignore_changes and replace_triggered_by.', 'lifecycle {\n  ignore_changes = [desired_capacity]\n}'],
  ['Intermediate', 'Remote state', 'Store state in S3 so a team shares one source of truth. From Terraform 1.10, S3 supports native locking with use_lockfile, so a DynamoDB lock table is no longer required.', 'backend "s3" {\n  bucket       = "my-tf-state"\n  key          = "app/terraform.tfstate"\n  region       = "ap-southeast-1"\n  use_lockfile = true\n}'],
  ['Advanced', 'Module design', 'Keep modules small and single-purpose, expose only the inputs callers need, output IDs and ARNs, avoid provider blocks inside child modules, and version them with semantic tags.', ''],
  ['Advanced', 'State management', 'Split state by blast radius (network, data, app) and lifecycle. Use moved blocks to rename safely, import blocks to adopt existing resources, and removed blocks to stop managing something without destroying it.', 'moved {\n  from = aws_instance.web\n  to   = aws_instance.main\n}'],
  ['Advanced', 'Workspaces', 'Multiple state files for one configuration. Handy for short-lived copies; for dev/staging/prod most teams prefer separate directories or accounts so permissions and backends differ.', 'terraform workspace new staging'],
  ['Advanced', 'Provider aliases', 'A second configuration of the same provider, for another region or account. Resources choose it with provider = aws.<alias>.', 'provider "aws" {\n  alias  = "us_east_1"\n  region = "us-east-1"\n}'],
  ['Advanced', 'Multi-account AWS', 'In a Control Tower or Organizations landing zone, Terraform runs with one identity and assumes a role in each target account.', 'provider "aws" {\n  alias  = "workload"\n  region = var.aws_region\n  assume_role {\n    role_arn = "arn:aws:iam::111122223333:role/TerraformDeploy"\n  }\n}'],
  ['Advanced', 'Multi-region AWS', 'Use one provider alias per region and pass providers into modules explicitly, or deploy the same root module per region with different variables.', 'module "dr" {\n  source    = "./modules/app"\n  providers = { aws = aws.dr }\n}'],
  ['Advanced', 'CI/CD', 'Run fmt, validate, plan on every pull request and apply only from the main branch with a reviewed plan. Authenticate with OIDC federation to an IAM role instead of stored keys.', ''],
  ['Advanced', 'HCP Terraform', 'HashiCorp\'s hosted service (formerly Terraform Cloud) that stores state, runs plans remotely, and adds policy checks and a private registry.', 'terraform {\n  cloud {\n    organization = "my-org"\n    workspaces { name = "network-dev" }\n  }\n}'],
  ['Advanced', 'State locking', 'Prevents two applies from writing the same state at once. S3 with use_lockfile, HCP Terraform and most backends lock automatically.', ''],
  ['Advanced', 'Security best practices', 'No credentials in code; least-privilege IAM; encrypt state and resources; mark secret outputs sensitive; scan with tools like tflint, checkov or trivy; pin provider and module versions; review every plan.', ''],
];

const CLI = [
  ['terraform init', 'Downloads the AWS and archive providers and prepares the working directory.'],
  ['terraform fmt', 'Rewrites files into canonical style. Use -check in CI to fail on unformatted code.'],
  ['terraform validate', 'Checks syntax, references and argument names against the provider schema. It needs init first and does not call AWS.'],
  ['terraform plan -out=tfplan', 'Compares your code with state and AWS, and saves the exact change set for review.'],
  ['terraform apply tfplan', 'Makes the reviewed changes. Without a plan file, apply plans again and asks for confirmation.'],
  ['terraform output', 'Prints outputs such as the ALB DNS name or database endpoint.'],
  ['terraform destroy', 'Removes everything this configuration created. Turn off deletion protection first.'],
];

const AUTH = [
  ['IAM Identity Center (AWS SSO)', 'Recommended for people. Run aws configure sso once, then aws sso login; export AWS_PROFILE to pick the profile.', 'aws sso login --profile learning\nexport AWS_PROFILE=learning'],
  ['AWS CLI profile', 'Named profiles in ~/.aws/config. Terraform reads AWS_PROFILE automatically; you do not need to set profile in the provider block.', 'export AWS_PROFILE=learning'],
  ['Environment variables', 'Short-lived credentials from STS can be exported as AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN. Never paste long-lived keys into .tf files.', ''],
  ['IAM role', 'On EC2, ECS, CodeBuild or a CI runner using OIDC, the provider picks up role credentials automatically. This is how pipelines should deploy.', ''],
];

// Community modules maintained by the terraform-aws-modules project on the Registry.
// Versions are intentionally not hard-coded here; pin the current one from the Registry page.
const MODULES = {
  vpc: { m: 'vpc', covers: ['vpc', 'subnet', 'route_table', 'igw', 'nat', 'eip', 'nacl', 'vgw'], inputs: ['name', 'cidr', 'azs', 'private_subnets', 'public_subnets', 'enable_nat_gateway', 'single_nat_gateway'], outputs: ['vpc_id', 'private_subnets', 'public_subnets', 'natgw_ids'] },
  vpc_endpoint: { m: 'vpc', sub: 'modules/vpc-endpoints', covers: ['vpc_endpoint'], inputs: ['vpc_id', 'endpoints'], outputs: ['endpoints'] },
  sg: { m: 'security-group', covers: ['sg'], inputs: ['name', 'vpc_id', 'ingress_cidr_blocks', 'ingress_rules', 'egress_rules'], outputs: ['security_group_id'] },
  tgw: { m: 'transit-gateway', covers: ['tgw', 'tgw_attach'] },
  alb: { m: 'alb', covers: ['alb', 'nlb', 'tg', 'listener'], inputs: ['name', 'load_balancer_type', 'vpc_id', 'subnets', 'listeners', 'target_groups'], outputs: ['arn', 'dns_name', 'target_groups'] },
  route53: { m: 'route53', covers: ['route53_zone', 'route53_record'] },
  cloudfront: { m: 'cloudfront', covers: ['cloudfront'] },
  vpn: { m: 'vpn-gateway', covers: ['vpn', 'cgw'] },
  ec2: { m: 'ec2-instance', covers: ['ec2'], inputs: ['name', 'ami', 'instance_type', 'subnet_id', 'vpc_security_group_ids'], outputs: ['id', 'private_ip', 'arn'] },
  asg: { m: 'autoscaling', covers: ['asg', 'lt'] },
  lambda: { m: 'lambda', covers: ['lambda'], inputs: ['function_name', 'handler', 'runtime', 'source_path'], outputs: ['lambda_function_arn', 'lambda_function_name'] },
  ecs: { m: 'ecs', covers: ['ecs_cluster', 'ecs_task', 'ecs_service'] },
  eks: { m: 'eks', covers: ['eks_cluster', 'eks_node_group'] },
  ecr: { m: 'ecr', covers: ['ecr'] },
  iam: { m: 'iam', covers: ['iam_role', 'iam_policy'] },
  ssm: { m: 'ssm-parameter', covers: ['ssm'] },
  rds: { m: 'rds', covers: ['rds', 'rds_postgres', 'rds_mysql', 'rds_sqlserver', 'dbsg'], inputs: ['identifier', 'engine', 'engine_version', 'instance_class', 'allocated_storage', 'db_subnet_group_name'], outputs: ['db_instance_endpoint', 'db_instance_arn'] },
  aurora: { m: 'rds-aurora', covers: ['aurora'] },
  dynamodb: { m: 'dynamodb-table', covers: ['dynamodb'], inputs: ['name', 'hash_key', 'range_key', 'attributes'], outputs: ['dynamodb_table_arn', 'dynamodb_table_id'] },
  elasticache: { m: 'elasticache', covers: ['elasticache'] },
  memorydb: { m: 'memory-db', covers: ['memorydb'] },
  s3: { m: 's3-bucket', covers: ['s3', 's3_versioning', 's3_encryption', 's3_lifecycle'], inputs: ['bucket', 'versioning', 'server_side_encryption_configuration', 'lifecycle_rule'], outputs: ['s3_bucket_id', 's3_bucket_arn'] },
  efs: { m: 'efs', covers: ['efs'] },
  fsx: { m: 'fsx', covers: ['fsx'] },
  kms: { m: 'kms', covers: ['kms'] },
  // The same project also publishes eventbridge and sns modules for the event and notification parts.
  cloudwatch: { m: 'cloudwatch', sub: 'modules/metric-alarm', covers: ['cloudwatch'] },
};
function moduleFor(svcId) { for (const [k, v] of Object.entries(MODULES)) if (v.covers.includes(svcId)) return Object.assign({ key: k }, v); return null; }
function moduleUrl(m) { return `https://registry.terraform.io/modules/terraform-aws-modules/${m.m}/aws/latest` + (m.sub ? '/submodules/' + m.sub.split('/').pop() : ''); }
